// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAkHlX8b_4KESKVYX6xuqB0PCEz9_KxYA',
    appId: '1:979478857644:web:5cc1f044e806fc346b1c09',
    messagingSenderId: '979478857644',
    projectId: 'dynamic-link-55f8f',
    authDomain: 'dynamic-link-55f8f.firebaseapp.com',
    storageBucket: 'dynamic-link-55f8f.appspot.com',
    measurementId: 'G-QZM2NPK9HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSPkL26wRyWO8lGzUCOFHNVzHLxntuL8',
    appId: '1:979478857644:android:a11a5c70cdf3b3a46b1c09',
    messagingSenderId: '979478857644',
    projectId: 'dynamic-link-55f8f',
    storageBucket: 'dynamic-link-55f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0Thr5cfeF5kZr6kMPqFWcr2gM-SA-oY',
    appId: '1:979478857644:ios:c2a79cbb22fe7f0d6b1c09',
    messagingSenderId: '979478857644',
    projectId: 'dynamic-link-55f8f',
    storageBucket: 'dynamic-link-55f8f.appspot.com',
    iosBundleId: 'com.example.dynamicLinkDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0Thr5cfeF5kZr6kMPqFWcr2gM-SA-oY',
    appId: '1:979478857644:ios:31db830febdb7d086b1c09',
    messagingSenderId: '979478857644',
    projectId: 'dynamic-link-55f8f',
    storageBucket: 'dynamic-link-55f8f.appspot.com',
    iosBundleId: 'com.example.dynamicLinkDemo.RunnerTests',
  );
}
